default: true

# Line length
MD013:
  line_length: 120

# Allow duplicate headings with different content (for CHANGELOG.md)
MD024:
  siblings_only: true

# Allow inline HTML (for <details> blocks)
MD033: false
